// ============================================================
// Prompt Templates — Pre-built prompts for each Office app
// ============================================================

import { PromptTemplate, OfficeHostType } from "../types";

export const PROMPT_TEMPLATES: PromptTemplate[] = [
  // ---- Excel: Analysis ----
  {
    id: "excel-analyze-selection",
    title: "Analyze Selected Data",
    description: "Get a statistical summary of the selected cells",
    prompt: "Analyze the selected data. Provide: count, sum, average, min, max, median, standard deviation, and any notable patterns or outliers. Format as a clear summary.",
    category: "analysis",
    hostApp: "Excel",
    icon: "📊",
  },
  {
    id: "excel-trend-analysis",
    title: "Trend Analysis",
    description: "Identify trends and patterns in your data",
    prompt: "Analyze the trends in this data. Identify: direction (increasing/decreasing/stable), rate of change, seasonal patterns, anomalies, and provide forecasting suggestions.",
    category: "analysis",
    hostApp: "Excel",
    icon: "📈",
  },
  {
    id: "excel-outlier-detection",
    title: "Detect Outliers",
    description: "Find outliers and anomalies",
    prompt: "Examine this data for outliers and anomalies. Use statistical methods (IQR, Z-score) to identify unusual values. Explain why each is flagged and suggest how to handle them.",
    category: "analysis",
    hostApp: "Excel",
    icon: "🔍",
  },
  {
    id: "excel-correlation",
    title: "Correlation Analysis",
    description: "Find relationships between columns",
    prompt: "Analyze the correlations between the columns in this data. Identify which variables are positively/negatively correlated, the strength of each relationship, and any surprising findings.",
    category: "analysis",
    hostApp: "Excel",
    icon: "🔗",
  },
  {
    id: "excel-duplicates",
    title: "Find Duplicates",
    description: "Detect duplicate rows or values",
    prompt: "Scan this data for duplicate values and rows. Report: which values appear more than once, their locations, and suggest a formula or approach to handle them.",
    category: "cleaning",
    hostApp: "Excel",
    icon: "🔄",
  },

  // ---- Excel: Formulas ----
  {
    id: "excel-explain-formula",
    title: "Explain Formula",
    description: "Break down a formula step by step",
    prompt: "Explain this Excel formula step by step in simple language. Break down each function, what it does, and how the parts work together. Also suggest if there's a simpler alternative.",
    category: "formula",
    hostApp: "Excel",
    icon: "🧮",
  },
  {
    id: "excel-generate-formula",
    title: "Generate Formula",
    description: "Create a formula from plain English",
    prompt: "Generate an Excel formula that does the following: [describe what you need]. Provide the formula, explain how it works, and give an example of how to use it.",
    category: "formula",
    hostApp: "Excel",
    icon: "✨",
  },
  {
    id: "excel-fix-formula",
    title: "Fix Formula Error",
    description: "Debug and fix formula errors",
    prompt: "This formula is producing an error. Diagnose the issue, explain why it's failing, and provide the corrected formula. Common issues to check: circular references, wrong range, missing parentheses, data type mismatches.",
    category: "formula",
    hostApp: "Excel",
    icon: "🔧",
  },
  {
    id: "excel-optimize-formula",
    title: "Optimize Formula",
    description: "Make a formula more efficient",
    prompt: "Review this formula and suggest optimizations. Consider: performance (avoid VLOOKUP in favor of INDEX/MATCH or XLOOKUP), readability, error handling (IFERROR), and modern Excel functions (FILTER, UNIQUE, SORT, LET).",
    category: "formula",
    hostApp: "Excel",
    icon: "⚡",
  },

  // ---- Excel: Charts ----
  {
    id: "excel-chart-recommend",
    title: "Recommend Chart",
    description: "Get the best chart type for your data",
    prompt: "Based on this data, recommend the best chart type(s) to visualize it. Consider: the data structure, what story it tells, and the audience. Suggest specific chart types with explanations.",
    category: "chart",
    hostApp: "Excel",
    icon: "📉",
  },

  // ---- Excel: Finance ----
  {
    id: "excel-budget-analysis",
    title: "Budget Analysis",
    description: "Analyze budget vs actual spending",
    prompt: "Analyze this budget data. Calculate: variance (amount and percentage), identify over/under-budget categories, suggest areas for cost reduction, and provide a summary dashboard formula set.",
    category: "finance",
    hostApp: "Excel",
    icon: "💰",
  },
  {
    id: "excel-financial-ratios",
    title: "Financial Ratios",
    description: "Calculate key financial ratios",
    prompt: "From this financial data, calculate key ratios: liquidity (current ratio, quick ratio), profitability (gross margin, net margin, ROE, ROA), efficiency (asset turnover, inventory turnover), and leverage (debt-to-equity). Provide formulas and interpretation.",
    category: "finance",
    hostApp: "Excel",
    icon: "📋",
  },
  {
    id: "excel-cashflow",
    title: "Cash Flow Analysis",
    description: "Analyze cash flow patterns",
    prompt: "Analyze the cash flow data. Identify: inflow/outflow patterns, net cash position trends, seasonal variations, and provide projections. Suggest formulas for a cash flow statement.",
    category: "finance",
    hostApp: "Excel",
    icon: "💵",
  },
  {
    id: "excel-breakeven",
    title: "Break-Even Analysis",
    description: "Calculate break-even point",
    prompt: "Using this data, calculate the break-even point. Consider: fixed costs, variable costs per unit, and selling price per unit. Provide the break-even formula in units and revenue, plus a sensitivity analysis.",
    category: "finance",
    hostApp: "Excel",
    icon: "⚖️",
  },

  // ---- Excel: Data Cleaning ----
  {
    id: "excel-clean-data",
    title: "Clean This Data",
    description: "AI-assisted data cleaning",
    prompt: "Review this data for quality issues. Check for: inconsistent formatting, mixed data types, extra spaces, special characters, missing values, typos, and inconsistent naming. Suggest specific formulas to fix each issue.",
    category: "cleaning",
    hostApp: "Excel",
    icon: "🧹",
  },
  {
    id: "excel-standardize-dates",
    title: "Standardize Dates",
    description: "Fix inconsistent date formats",
    prompt: "These cells contain dates in various formats. Identify all the different formats present and provide a formula to convert them all to a standard format (YYYY-MM-DD). Handle edge cases like text dates.",
    category: "cleaning",
    hostApp: "Excel",
    icon: "📅",
  },

  // ---- Excel: Code Generation ----
  {
    id: "excel-vba-macro",
    title: "Generate VBA Macro",
    description: "Create a VBA macro for automation",
    prompt: "Generate a VBA macro that does the following: [describe the task]. Include: proper error handling, comments explaining each step, and instructions on how to add it to the workbook (Alt+F11).",
    category: "code",
    hostApp: "Excel",
    icon: "⚙️",
  },
  {
    id: "excel-office-script",
    title: "Generate Office Script",
    description: "Create an Office Script (TypeScript)",
    prompt: "Generate an Office Script (TypeScript) that does the following: [describe the task]. Include comments and explain how to run it from the Automate tab in Excel.",
    category: "code",
    hostApp: "Excel",
    icon: "📜",
  },
  {
    id: "excel-power-query",
    title: "Generate Power Query (M)",
    description: "Create Power Query M code",
    prompt: "Generate Power Query M code that does the following: [describe the data transformation]. Include step-by-step comments and instructions on how to paste it into the Advanced Editor.",
    category: "code",
    hostApp: "Excel",
    icon: "🔌",
  },
  {
    id: "excel-sql",
    title: "Generate SQL Query",
    description: "Create SQL from your data structure",
    prompt: "Based on this data structure, generate SQL queries for: creating the table, inserting the data, and common queries (SELECT, GROUP BY, JOIN, aggregations). Use standard SQL syntax.",
    category: "code",
    hostApp: "Excel",
    icon: "🗃️",
  },

  // ---- Word: Writing ----
  {
    id: "word-rewrite",
    title: "Rewrite Text",
    description: "Rewrite selected text professionally",
    prompt: "Rewrite the following text to be more professional, clear, and concise. Maintain the original meaning but improve the language, structure, and flow. Provide the rewritten version.",
    category: "writing",
    hostApp: "Word",
    icon: "✏️",
  },
  {
    id: "word-summarize",
    title: "Summarize Document",
    description: "Create a concise summary",
    prompt: "Summarize this text concisely. Provide: a one-paragraph executive summary, followed by key points as bullet points. Keep it under 200 words.",
    category: "writing",
    hostApp: "Word",
    icon: "📝",
  },
  {
    id: "word-grammar",
    title: "Fix Grammar & Style",
    description: "Correct grammar, spelling, and style",
    prompt: "Review this text for grammar, spelling, punctuation, and style errors. For each issue: quote the problematic text, explain the error, and provide the correction. Then provide the fully corrected version.",
    category: "writing",
    hostApp: "Word",
    icon: "✅",
  },
  {
    id: "word-expand",
    title: "Expand Content",
    description: "Add more detail and depth",
    prompt: "Expand this text by adding more detail, examples, and depth while maintaining the same tone and style. Aim for roughly 2-3x the original length.",
    category: "writing",
    hostApp: "Word",
    icon: "📖",
  },
  {
    id: "word-shorten",
    title: "Shorten Content",
    description: "Make text more concise",
    prompt: "Condense this text to about half its length while preserving all key information and meaning. Remove redundancy, simplify sentences, and tighten the prose.",
    category: "writing",
    hostApp: "Word",
    icon: "✂️",
  },
  {
    id: "word-formal",
    title: "Make Formal",
    description: "Convert to formal/business tone",
    prompt: "Rewrite this text in a formal, professional business tone suitable for official correspondence, reports, or executive communication. Maintain accuracy.",
    category: "writing",
    hostApp: "Word",
    icon: "👔",
  },
  {
    id: "word-casual",
    title: "Make Casual",
    description: "Convert to friendly, casual tone",
    prompt: "Rewrite this text in a friendly, conversational tone suitable for blog posts, newsletters, or informal communication. Keep it engaging and approachable.",
    category: "writing",
    hostApp: "Word",
    icon: "😊",
  },
  {
    id: "word-report",
    title: "Generate Report",
    description: "Create a structured report",
    prompt: "Generate a professional report based on this content. Include: title, executive summary, introduction, main sections with headings, findings/analysis, conclusions, and recommendations. Format with proper headings.",
    category: "writing",
    hostApp: "Word",
    icon: "📄",
  },
  {
    id: "word-email",
    title: "Draft Email",
    description: "Create a professional email",
    prompt: "Draft a professional email based on this context. Include: subject line, greeting, clear body with purpose, action items, and a professional closing. Keep it concise.",
    category: "writing",
    hostApp: "Word",
    icon: "📧",
  },
  {
    id: "word-meeting-notes",
    title: "Meeting Notes",
    description: "Format as meeting minutes",
    prompt: "Format this content as professional meeting minutes. Include: date, attendees (if mentioned), agenda items, discussion points, decisions made, action items with owners and deadlines, and next steps.",
    category: "writing",
    hostApp: "Word",
    icon: "📋",
  },

  // ---- PowerPoint: Presentation ----
  {
    id: "ppt-improve-slide",
    title: "Improve Slide Text",
    description: "Make slide text more impactful",
    prompt: "Improve this slide text to be more impactful and presentation-ready. Use: concise bullet points, active voice, powerful verbs, and clear messaging. Keep each bullet under 10 words.",
    category: "presentation",
    hostApp: "PowerPoint",
    icon: "🎯",
  },
  {
    id: "ppt-speaker-notes",
    title: "Generate Speaker Notes",
    description: "Create detailed speaker notes",
    prompt: "Generate detailed speaker notes for this slide content. Include: what to say, key talking points, transitions to the next slide, and audience engagement tips. Write in a natural speaking style.",
    category: "presentation",
    hostApp: "PowerPoint",
    icon: "🎤",
  },
  {
    id: "ppt-script",
    title: "Presentation Script",
    description: "Write a full presentation script",
    prompt: "Write a complete presentation script for these slides. Include: opening hook, transitions between slides, key messages to emphasize, storytelling elements, and a strong closing. Aim for 2-3 minutes per slide.",
    category: "presentation",
    hostApp: "PowerPoint",
    icon: "📜",
  },
  {
    id: "ppt-generate-outline",
    title: "Generate Slide Outline",
    description: "Create a presentation structure",
    prompt: "Create a professional presentation outline from this content. Include: title slide, agenda, 5-8 content slides with bullet points, key visuals to include, and a closing slide. Format as slide-by-slide with titles and bullets.",
    category: "presentation",
    hostApp: "PowerPoint",
    icon: "📑",
  },
  {
    id: "ppt-board-ready",
    title: "Board Meeting Ready",
    description: "Adapt for executive audience",
    prompt: "Adapt this slide content for a board/executive meeting. Focus on: strategic impact, KPIs, financial implications, risks, and recommendations. Use concise, data-driven language. Remove operational details.",
    category: "presentation",
    hostApp: "PowerPoint",
    icon: "🏛️",
  },
  {
    id: "ppt-qa-prep",
    title: "Q&A Preparation",
    description: "Prepare for audience questions",
    prompt: "Based on this presentation content, prepare for Q&A. Generate: 10 likely questions the audience might ask, with recommended answers for each. Include tough/challenging questions too.",
    category: "presentation",
    hostApp: "PowerPoint",
    icon: "❓",
  },

  // ---- General / All Apps ----
  {
    id: "general-translate",
    title: "Translate",
    description: "Translate text to another language",
    prompt: "Translate the following text to [target language]. Maintain the original formatting, tone, and meaning. If there are cultural nuances, note them.",
    category: "translate",
    hostApp: "All",
    icon: "🌐",
  },
  {
    id: "general-sentiment",
    title: "Sentiment Analysis",
    description: "Analyze the sentiment of text",
    prompt: "Analyze the sentiment of this text. Provide: overall sentiment (positive/negative/neutral), confidence score, key phrases driving the sentiment, and a breakdown by paragraph/section if applicable.",
    category: "analysis",
    hostApp: "All",
    icon: "💬",
  },
  {
    id: "general-classify",
    title: "Classify & Tag",
    description: "Categorize and tag content",
    prompt: "Classify and tag this content. Suggest: primary category, subcategories, relevant tags/keywords, and a confidence level for each classification. Base categories on the content type.",
    category: "general",
    hostApp: "All",
    icon: "🏷️",
  },
  {
    id: "general-extract-entities",
    title: "Extract Entities",
    description: "Find names, dates, amounts, etc.",
    prompt: "Extract all named entities from this text. Categorize them: people, organizations, locations, dates, monetary amounts, percentages, products, and other. Format as a structured list.",
    category: "general",
    hostApp: "All",
    icon: "🔎",
  },
  {
    id: "general-explain",
    title: "Explain Simply",
    description: "Explain complex content simply",
    prompt: "Explain this content in simple, easy-to-understand language. Assume the reader has no prior knowledge of the subject. Use analogies and examples where helpful.",
    category: "general",
    hostApp: "All",
    icon: "💡",
  },
  {
    id: "general-python",
    title: "Generate Python Code",
    description: "Create Python code for data tasks",
    prompt: "Generate Python code (using pandas) that works with this data structure. Include: data loading, the requested transformation/analysis, and output formatting. Add comments explaining each step.",
    category: "code",
    hostApp: "All",
    icon: "🐍",
  },

  // ---- Cross-App: CA Study Assistant & Accounting ----
  {
    id: "ca-study-assistant",
    title: "CA Study Assistant",
    description: "Get help with CA exam topics and concepts",
    prompt: "You are a Chartered Accountancy (CA) study assistant. Help me understand the following CA exam topic. Provide: a clear concept explanation, key points to remember, common exam question patterns, relevant sections/standards, and mnemonic tricks if applicable. Topic: [describe your CA study topic or question]",
    category: "accounting",
    hostApp: "All",
    icon: "🎓",
  },
  {
    id: "ca-practice-question",
    title: "CA Practice Question",
    description: "Generate and solve CA practice questions",
    prompt: "Generate a CA exam-style practice question on the following topic, then provide a detailed step-by-step solution. Include: the question, relevant standard/section references, a worked solution with proper workings, and common mistakes to avoid. Topic: [describe the CA subject or chapter]",
    category: "accounting",
    hostApp: "All",
    icon: "📝",
  },
  {
    id: "ifrs-term-explainer",
    title: "IAS/IFRS Term Explainer",
    description: "Explain IAS/IFRS terms and standards",
    prompt: "Explain the following IAS/IFRS accounting term or standard in simple, clear language. Include: the full standard name and number, its purpose and scope, key definitions, recognition and measurement criteria, disclosure requirements, practical examples, and any recent amendments. Term/Standard: [enter the IAS/IFRS term or standard number]",
    category: "accounting",
    hostApp: "All",
    icon: "📚",
  },
  {
    id: "ifrs-journal-entry",
    title: "IFRS Journal Entry Helper",
    description: "Generate journal entries under IAS/IFRS",
    prompt: "Help me prepare the correct journal entries under IAS/IFRS for the following transaction. Include: the journal entry with proper debits and credits, the relevant IAS/IFRS standard reference, explanation of the accounting treatment, subsequent measurement entries if applicable, and disclosure notes. Transaction: [describe the accounting transaction]",
    category: "accounting",
    hostApp: "All",
    icon: "📋",
  },
  {
    id: "ifrs-vs-gaap",
    title: "IFRS vs GAAP Comparison",
    description: "Compare IAS/IFRS and US GAAP treatments",
    prompt: "Compare the IAS/IFRS and US GAAP treatment for the following accounting topic. Include: key similarities, key differences, relevant standard numbers from both frameworks, practical examples showing how the same transaction would be recorded differently, and which treatment is more conservative. Topic: [describe the accounting area]",
    category: "accounting",
    hostApp: "All",
    icon: "⚖️",
  },  {
    id: "ex-vba-writer",
    title: "VBA Macro Writer",
    description: "Write VBA code to automate tasks",
    prompt: "Write an Excel VBA macro to automate the following task: [describe task]. Include comments explaining the code and instructions on how to run it.",
    category: "code",
    hostApp: "Excel",
    icon: "📜",
  },
  {
    id: "ex-vba-explainer",
    title: "VBA Explainer",
    description: "Explain existing VBA code",
    prompt: "Explain what this VBA code does step-by-step. Identify any potential errors, inefficiencies, or security risks.",
    category: "code",
    hostApp: "Excel",
    icon: "🕵️",
  },
  {
    id: "ex-powerquery",
    title: "Power Query M Code Writer",
    description: "Write advanced M code for Power Query",
    prompt: "Write Power Query M code to perform the following data transformation: [describe transformation].",
    category: "code",
    hostApp: "Excel",
    icon: "⚡",
  },
  {
    id: "ex-pivot",
    title: "Pivot Table Assistant",
    description: "Suggest pivot table layouts",
    prompt: "Based on this dataset, suggest 3 useful Pivot Table layouts. Specify what fields to put in Rows, Columns, Values (with aggregation type), and Filters.",
    category: "analysis",
    hostApp: "Excel",
    icon: "🗂️",
  },
  {
    id: "ex-cond-format",
    title: "Conditional Formatting Helper",
    description: "Generate conditional formatting formulas",
    prompt: "Provide the exact formula and steps to apply conditional formatting to achieve this result: [describe desired formatting rule].",
    category: "formula",
    hostApp: "Excel",
    icon: "🎨",
  },
  {
    id: "ex-dashboard-layout",
    title: "Dashboard Layout Advisor",
    description: "Suggest a layout for an Excel dashboard",
    prompt: "Suggest a layout and structure for a professional Excel dashboard using this data. What KPIs should be at the top, what charts in the middle, and what data tables at the bottom?",
    category: "analysis",
    hostApp: "Excel",
    icon: "🖥️",
  },
  {
    id: "ex-lookup",
    title: "SUMIF/VLOOKUP/XLOOKUP Specialist",
    description: "Write complex lookup and aggregation formulas",
    prompt: "Write an advanced lookup or aggregation formula (e.g., XLOOKUP, INDEX/MATCH, SUMIFS) to solve this problem: [describe lookup requirement].",
    category: "formula",
    hostApp: "Excel",
    icon: "🔍",
  },
  {
    id: "ex-array",
    title: "Array Formula Helper",
    description: "Write modern dynamic array formulas",
    prompt: "Write a modern dynamic array formula (using FILTER, SORT, UNIQUE, SEQUENCE, etc.) to accomplish this task: [describe task].",
    category: "formula",
    hostApp: "Excel",
    icon: "🧮",
  },
  {
    id: "ex-validation",
    title: "Data Validation Rules",
    description: "Create custom data validation formulas",
    prompt: "Provide a custom Data Validation formula to enforce the following rule: [describe rule, e.g., only allow alphanumeric, prevent duplicates].",
    category: "formula",
    hostApp: "Excel",
    icon: "🛡️",
  },
  {
    id: "ex-named-ranges",
    title: "Named Ranges Manager",
    description: "Suggest naming conventions and dynamic ranges",
    prompt: "Suggest a naming convention for the key variables in this data, and provide the formula to create a dynamic named range (using OFFSET/COUNTA or tables) for this column.",
    category: "formula",
    hostApp: "Excel",
    icon: "🏷️",
  },
  {
    id: "ex-what-if",
    title: "What-If Analysis Assistant",
    description: "Set up scenarios or goal seek",
    prompt: "Explain how to set up a What-If Analysis (Data Table, Scenario Manager, or Goal Seek) for this financial model to determine: [describe objective].",
    category: "analysis",
    hostApp: "Excel",
    icon: "❓",
  },
  {
    id: "ex-fin-ratio",
    title: "Financial Ratio Calculator",
    description: "Calculate standard financial ratios",
    prompt: "Calculate key financial ratios (Current Ratio, Quick Ratio, Debt-to-Equity, Gross Margin, ROE) based on this financial data. Show the formulas used.",
    category: "finance",
    hostApp: "Excel",
    icon: "➗",
  },
  {
    id: "ex-reconciliation",
    title: "Reconciliation Checker",
    description: "Compare two lists to find discrepancies",
    prompt: "I have two lists (e.g., Book vs. Bank, System A vs. System B). Provide a formula or Power Query method to identify missing items and value discrepancies.",
    category: "cleaning",
    hostApp: "Excel",
    icon: "⚖️",
  },
  {
    id: "ex-scenario",
    title: "Scenario Analysis Assistant",
    description: "Build Best/Base/Worst case scenarios",
    prompt: "Help me structure a Best Case, Base Case, and Worst Case scenario for this projection. Suggest formulas (like CHOOSE) to toggle between them.",
    category: "finance",
    hostApp: "Excel",
    icon: "🎭",
  },
  {
    id: "ex-sensitivity",
    title: "Sensitivity Analysis Helper",
    description: "Analyze impact of variable changes",
    prompt: "Suggest how to build a sensitivity analysis table (1-way or 2-way Data Table) for this model to see how changes in [Variable A] and [Variable B] impact the final output.",
    category: "finance",
    hostApp: "Excel",
    icon: "🌡️",
  },
  {
    id: "ex-budget-actual",
    title: "Budget vs Actual Analyser",
    description: "Analyze budget variances",
    prompt: "Analyze this Budget vs. Actual data. Calculate the absolute and percentage variances, flag significant deviations, and suggest possible reasons.",
    category: "finance",
    hostApp: "Excel",
    icon: "📊",
  },
  {
    id: "ex-forecasting",
    title: "Forecasting Formula Writer",
    description: "Write forecasting and trend formulas",
    prompt: "Provide formulas (like FORECAST.ETS, TREND, or moving averages) to project the next 12 periods based on this historical data.",
    category: "finance",
    hostApp: "Excel",
    icon: "📈",
  },
  {
    id: "ex-amortisation",
    title: "Amortisation Schedule Builder",
    description: "Build a loan amortisation table",
    prompt: "Provide the exact columns, headers, and formulas (PMT, PPMT, IPMT) needed to build a complete loan amortization schedule.",
    category: "finance",
    hostApp: "Excel",
    icon: "🗓️",
  },
  {
    id: "ex-depreciation",
    title: "Depreciation Calculator",
    description: "Calculate asset depreciation",
    prompt: "Calculate the depreciation schedule for this asset using Straight Line (SLN), Declining Balance (DB), and Sum-of-Years' Digits (SYD) methods.",
    category: "finance",
    hostApp: "Excel",
    icon: "📉",
  },
  {
    id: "ex-cashflow",
    title: "Cash Flow Statement Builder",
    description: "Build a Cash Flow statement",
    prompt: "Based on this Income Statement and comparative Balance Sheet, guide me step-by-step to build a Statement of Cash Flows using the indirect method.",
    category: "finance",
    hostApp: "Excel",
    icon: "💵",
  },
  {
    id: "ex-aging",
    title: "Aging Report Analyser",
    description: "Analyze AR/AP aging",
    prompt: "Analyze this Accounts Receivable/Payable aging report. Group the data into 30/60/90+ day buckets and calculate the percentage of total outstanding.",
    category: "finance",
    hostApp: "Excel",
    icon: "⏳",
  },
  {
    id: "ex-benchmark",
    title: "Benchmark Comparator",
    description: "Compare data against benchmarks",
    prompt: "Compare these company metrics against the provided industry benchmarks. Highlight areas of overperformance and underperformance.",
    category: "analysis",
    hostApp: "Excel",
    icon: "🥇",
  },
  {
    id: "wd-rewriter",
    title: "Professional Rewriter",
    description: "Rewrite text in a professional tone",
    prompt: "Rewrite the following text to sound more professional, polished, and corporate, while maintaining the original meaning.",
    category: "writing",
    hostApp: "Word",
    icon: "👔",
  },
  {
    id: "wd-grammar",
    title: "Grammar & Style Checker",
    description: "Check for grammar and style issues",
    prompt: "Review this document for grammatical errors, typos, awkward phrasing, and passive voice. Suggest specific corrections.",
    category: "writing",
    hostApp: "Word",
    icon: "✅",
  },
  {
    id: "wd-summariser",
    title: "Document Summariser",
    description: "Summarize a long document",
    prompt: "Provide a comprehensive summary of this document. Include the main thesis, key arguments, and final conclusions.",
    category: "writing",
    hostApp: "Word",
    icon: "📑",
  },
  {
    id: "wd-cover-letter",
    title: "Cover Letter Drafter",
    description: "Draft a professional cover letter",
    prompt: "Draft a professional cover letter based on this resume and job description. Highlight relevant skills and express enthusiasm.",
    category: "writing",
    hostApp: "Word",
    icon: "✉️",
  },
  {
    id: "wd-email",
    title: "Email Drafter",
    description: "Draft a professional email",
    prompt: "Draft a professional email addressing the following points: [list points]. Make the tone polite but firm.",
    category: "writing",
    hostApp: "Word",
    icon: "📧",
  },
  {
    id: "wd-report-format",
    title: "Report Formatter",
    description: "Suggest structure for a report",
    prompt: "Suggest a professional structure/table of contents for a formal business report on the following topic.",
    category: "writing",
    hostApp: "Word",
    icon: "📋",
  },
  {
    id: "wd-proofreader",
    title: "Proofreader",
    description: "Meticulous proofreading",
    prompt: "Act as a meticulous proofreader. Find any spelling, punctuation, or formatting inconsistencies in this text.",
    category: "writing",
    hostApp: "Word",
    icon: "🔍",
  },
  {
    id: "wd-tone",
    title: "Tone Adjuster",
    description: "Adjust the tone of the text",
    prompt: "Adjust the tone of this text to be more [persuasive / empathetic / urgent / objective].",
    category: "writing",
    hostApp: "Word",
    icon: "🎛️",
  },
  {
    id: "wd-expand-shorten",
    title: "Paragraph Expander/Shortener",
    description: "Change the length of a paragraph",
    prompt: "Rewrite this paragraph. First, provide an expanded version with more detail. Second, provide a highly condensed, punchy version.",
    category: "writing",
    hostApp: "Word",
    icon: "↕️",
  },
  {
    id: "wd-audit-report",
    title: "Audit Report Writer",
    description: "Draft a formal audit report",
    prompt: "Draft a formal audit report based on these findings. Include the Independent Auditor's Report structure (Opinion, Basis for Opinion, Key Audit Matters).",
    category: "audit",
    hostApp: "Word",
    icon: "📝",
  },
  {
    id: "wd-minutes",
    title: "Meeting Minutes Formatter",
    description: "Format meeting notes into minutes",
    prompt: "Format these rough meeting notes into professional meeting minutes. Include: Attendees, Key Decisions, and Action Items (with owners and deadlines).",
    category: "writing",
    hostApp: "Word",
    icon: "⏱️",
  },
  {
    id: "wd-proposal",
    title: "Proposal Writer",
    description: "Draft a business proposal",
    prompt: "Draft a business proposal for the following service/project. Include: Executive Summary, Problem Statement, Proposed Solution, Pricing, and Timeline.",
    category: "writing",
    hostApp: "Word",
    icon: "💼",
  },
  {
    id: "wd-engagement",
    title: "Engagement Letter Drafter",
    description: "Draft a professional engagement letter",
    prompt: "Draft a professional client engagement letter for [Service]. Include sections on Objective, Scope, Responsibilities of Management, and Fees.",
    category: "ca",
    hostApp: "Word",
    icon: "🤝",
  },
  {
    id: "wd-mrl",
    title: "Management Representation Letter",
    description: "Draft an MRL",
    prompt: "Draft a Management Representation Letter (MRL) for a statutory audit, confirming management's responsibilities for the financial statements and internal controls.",
    category: "audit",
    hostApp: "Word",
    icon: "📜",
  },
  {
    id: "wd-audit-opinion",
    title: "Audit Opinion Drafter",
    description: "Draft qualified/adverse opinions",
    prompt: "Draft the 'Basis for Qualified/Adverse Opinion' paragraph for an audit report based on the following specific misstatement or scope limitation.",
    category: "audit",
    hostApp: "Word",
    icon: "⚖️",
  },
  {
    id: "wd-internal-audit",
    title: "Internal Audit Report Formatter",
    description: "Format internal audit reports",
    prompt: "Format these internal audit findings into a standard report. Group by risk rating (High/Medium/Low) and ensure each has a clear Management Response section.",
    category: "audit",
    hostApp: "Word",
    icon: "🔎",
  },
  {
    id: "ppt-content",
    title: "Slide Content Generator",
    description: "Generate bullet points for a slide",
    prompt: "Generate 3-5 punchy, impactful bullet points for a presentation slide on the following topic.",
    category: "presentation",
    hostApp: "PowerPoint",
    icon: "📝",
  },
  {
    id: "ppt-speaker-notes",
    title: "Speaker Notes Writer",
    description: "Write speaker notes for slides",
    prompt: "Write engaging, conversational speaker notes for this slide content. Include cues for when to click or transition.",
    category: "presentation",
    hostApp: "PowerPoint",
    icon: "🎤",
  },
  {
    id: "ppt-structure",
    title: "Presentation Structure Suggester",
    description: "Suggest a presentation outline",
    prompt: "Suggest a 10-slide outline for a presentation to executives about [Topic]. What should be on each slide?",
    category: "presentation",
    hostApp: "PowerPoint",
    icon: "📑",
  },
  {
    id: "ppt-summariser",
    title: "Slide Summariser",
    description: "Summarize a dense slide",
    prompt: "This slide is too wordy. Summarize the text into 3 concise bullet points suitable for a presentation.",
    category: "presentation",
    hostApp: "PowerPoint",
    icon: "✂️",
  },
  {
    id: "ppt-title",
    title: "Title/Headline Writer",
    description: "Write catchy slide titles",
    prompt: "Suggest 5 catchy, action-oriented titles/headlines for a slide containing this data/information.",
    category: "presentation",
    hostApp: "PowerPoint",
    icon: "🏷️",
  },
  {
    id: "ppt-exec-advisor",
    title: "Executive Presentation Advisor",
    description: "Critique slides for an executive audience",
    prompt: "Review this slide content from the perspective of a C-level executive. Is it too detailed? Does it lead with the conclusion (BLUF)? Suggest improvements.",
    category: "presentation",
    hostApp: "PowerPoint",
    icon: "👔",
  },
  {
    id: "ppt-data-to-slide",
    title: "Data-to-Slide Converter",
    description: "Convert data to slide takeaways",
    prompt: "Convert this data table into a key takeaway statement and 3 supporting bullets suitable for a slide.",
    category: "presentation",
    hostApp: "PowerPoint",
    icon: "📊",
  },
  {
    id: "ppt-fin-dash",
    title: "Financial Dashboard to Slide",
    description: "Convert financial data to slide narrative",
    prompt: "Take this financial dashboard data and craft a compelling narrative for a Board of Directors presentation slide.",
    category: "presentation",
    hostApp: "PowerPoint",
    icon: "💰",
  },
  {
    id: "ppt-infographic",
    title: "Infographic Content Suggester",
    description: "Suggest ideas for infographics",
    prompt: "Suggest how to visually represent this text as an infographic on a slide (e.g., process flow, comparison table, pie chart).",
    category: "presentation",
    hostApp: "PowerPoint",
    icon: "🎨",
  },
  {
    id: "ppt-annual-report",
    title: "Annual Report Slide Builder",
    description: "Build slides for an annual report",
    prompt: "Suggest the key metrics and narrative structure for an 'Annual Performance Highlights' slide.",
    category: "presentation",
    hostApp: "PowerPoint",
    icon: "📅",
  },
  {
    id: "rep-financial",
    title: "Financial Report Generator",
    description: "Draft a comprehensive financial report",
    prompt: "Generate a professional financial report based on this data. Include an executive summary, financial performance overview, cash flow analysis, and forward-looking statements.",
    category: "reporting",
    hostApp: "Word",
    icon: "📈",
  },
  {
    id: "rep-management",
    title: "Management Report Drafter",
    description: "Draft a report for internal management",
    prompt: "Draft a management report focusing on operational performance, KPI achievement against targets, budget variances, and strategic recommendations.",
    category: "reporting",
    hostApp: "Word",
    icon: "👔",
  },
  {
    id: "rep-variance",
    title: "Variance Analysis Narrator",
    description: "Write commentary on budget variances",
    prompt: "Write clear, professional commentary explaining these budget-to-actual variances. Highlight the root causes (volume vs. price/rate) and suggest corrective actions.",
    category: "reporting",
    hostApp: "Excel",
    icon: "📉",
  },
  {
    id: "rep-kpi-dashboard",
    title: "KPI Dashboard Commentary",
    description: "Generate text for a KPI dashboard",
    prompt: "Generate concise, impactful commentary for a KPI dashboard based on these metrics. Focus on trends, outliers, and action items.",
    category: "reporting",
    hostApp: "Excel",
    icon: "📊",
  },
  {
    id: "rep-board",
    title: "Board Report Writer",
    description: "Draft a high-level report for the Board of Directors",
    prompt: "Draft a high-level, strategic report for the Board of Directors. Focus on major achievements, risks, strategic initiatives, and governance matters.",
    category: "reporting",
    hostApp: "Word",
    icon: "🏛️",
  },
  {
    id: "rep-monthly",
    title: "Monthly/Quarterly Template Filler",
    description: "Fill in standard reporting templates",
    prompt: "Take this raw financial data and format it into a standard monthly/quarterly performance narrative.",
    category: "reporting",
    hostApp: "Word",
    icon: "📅",
  },
  {
    id: "rep-ratio",
    title: "Ratio Analysis Report",
    description: "Write a report based on financial ratios",
    prompt: "Write a comprehensive ratio analysis report. Group by liquidity, profitability, efficiency, and solvency. Interpret what the ratios indicate about the company's health.",
    category: "reporting",
    hostApp: "Word",
    icon: "➗",
  },
  {
    id: "rep-audit-findings",
    title: "Audit Findings Report",
    description: "Draft an audit management letter",
    prompt: "Draft a professional audit findings report (management letter). For each issue, include: Observation, Risk/Implication, and Recommendation.",
    category: "reporting",
    hostApp: "Word",
    icon: "🚨",
  },
  {
    id: "rep-exec-summary",
    title: "Executive Summary from Data",
    description: "Summarize data for executives",
    prompt: "Analyze this dataset and generate a 1-page executive summary. Highlight only the most critical insights, financial impacts, and strategic takeaways.",
    category: "reporting",
    hostApp: "Word",
    icon: "📑",
  },
  {
    id: "rep-narrative",
    title: "Narrative from Numbers",
    description: "Convert a data table into a story",
    prompt: "Convert this table of numbers into a compelling business narrative. Explain the 'why' behind the numbers in professional prose.",
    category: "reporting",
    hostApp: "Word",
    icon: "✍️",
  },
  {
    id: "rep-data-story",
    title: "Data Storytelling Assistant",
    description: "Help craft a story from data",
    prompt: "Help me structure a presentation or report based on this data. What is the main hook, the supporting evidence, and the call to action?",
    category: "reporting",
    hostApp: "All",
    icon: "🗣️",
  },
  {
    id: "rep-chart-commentary",
    title: "Commentary from Charts",
    description: "Write commentary for visual data",
    prompt: "Based on the data shown in this chart/table, write a brief, insightful commentary caption that highlights the key takeaway.",
    category: "reporting",
    hostApp: "All",
    icon: "💬",
  },
  {
    id: "ca-ias-explainer",
    title: "IAS/IFRS Explainer",
    description: "Explain complex accounting standards",
    prompt: "Explain the following IAS/IFRS standard in clear, professional terms. Break down the core principles, recognition criteria, measurement, and disclosure requirements.",
    category: "ca",
    hostApp: "All",
    icon: "📖",
  },
  {
    id: "ca-audit-procedure",
    title: "Audit Procedure Suggester",
    description: "Suggest audit procedures for a specific area",
    prompt: "Suggest a comprehensive list of substantive and analytical audit procedures for the following financial statement area or assertion.",
    category: "audit",
    hostApp: "All",
    icon: "🔎",
  },
  {
    id: "ca-journal-entry-checker",
    title: "Journal Entry Checker",
    description: "Verify complex journal entries",
    prompt: "Review these journal entries for accuracy under applicable accounting standards. Identify any missing entries, incorrect accounts, or logic errors.",
    category: "ca",
    hostApp: "Excel",
    icon: "⚖️",
  },
  {
    id: "ca-deferred-tax",
    title: "Deferred Tax Calculator",
    description: "Help calculate deferred tax assets/liabilities",
    prompt: "Assist in calculating deferred tax. Identify temporary differences between the carrying amount and tax base, apply the relevant tax rate, and determine if a DTA or DTL should be recognized.",
    category: "ca",
    hostApp: "Excel",
    icon: "🧮",
  },
  {
    id: "ca-bank-recon",
    title: "Bank Reconciliation Assistant",
    description: "Help with complex bank recons",
    prompt: "Analyze this bank reconciliation data. Identify outstanding checks, deposits in transit, bank errors, or book errors. Suggest the necessary adjusting journal entries.",
    category: "ca",
    hostApp: "Excel",
    icon: "🏦",
  },
  {
    id: "ca-fin-stat-analyser",
    title: "Financial Statement Analyser",
    description: "Deep dive into financial statements",
    prompt: "Perform a detailed analysis of these financial statements. Highlight key liquidity, solvency, and profitability trends. Identify any red flags or areas requiring further audit scrutiny.",
    category: "ca",
    hostApp: "Excel",
    icon: "📊",
  },
  {
    id: "ca-audit-risk",
    title: "Audit Risk Identifier",
    description: "Identify risks of material misstatement",
    prompt: "Based on this client profile and financial data, identify the key inherent and control risks. Suggest the overall audit response and specific procedures to mitigate these risks.",
    category: "audit",
    hostApp: "Word",
    icon: "⚠️",
  },
  {
    id: "ca-internal-control",
    title: "Internal Control Checklist",
    description: "Generate a checklist for ICFR",
    prompt: "Generate a comprehensive internal control checklist for the specified business process (e.g., Procure-to-Pay, Order-to-Cash). Include preventative and detective controls.",
    category: "audit",
    hostApp: "Word",
    icon: "✅",
  },
  {
    id: "ca-working-paper",
    title: "Working Paper Drafter",
    description: "Draft professional audit working papers",
    prompt: "Draft a professional audit working paper for this testing area. Include: Objective, Scope, Methodology, Results/Exceptions, and Conclusion.",
    category: "audit",
    hostApp: "Word",
    icon: "📄",
  },
  {
    id: "ca-going-concern",
    title: "Going Concern Assessment",
    description: "Assist with going concern evaluation",
    prompt: "Evaluate these financial indicators and management plans for going concern issues. List mitigating factors and suggest required disclosures under ISA 570.",
    category: "audit",
    hostApp: "Word",
    icon: "🏢",
  },
  {
    id: "ca-materiality",
    title: "Materiality Calculator",
    description: "Calculate planning and performance materiality",
    prompt: "Suggest the appropriate benchmarks (e.g., % of revenue, % of PBT) and calculate overall materiality, performance materiality, and the trivial threshold for this engagement.",
    category: "audit",
    hostApp: "Excel",
    icon: "📐",
  },
  {
    id: "ca-sample-size",
    title: "Sample Size Suggester",
    description: "Suggest audit sample sizes based on risk",
    prompt: "Based on the assessed risk of material misstatement (High/Medium/Low) and tolerable error, suggest an appropriate statistical or non-statistical sample size for this test of details.",
    category: "audit",
    hostApp: "Excel",
    icon: "🔢",
  },
  {
    id: "ca-audit-programme",
    title: "Audit Programme Builder",
    description: "Build a customized audit programme",
    prompt: "Create a detailed audit programme for this specific account balance or class of transactions. Include objectives and step-by-step procedures.",
    category: "audit",
    hostApp: "Word",
    icon: "📝",
  },
  {
    id: "ca-disclosure",
    title: "Disclosure Checklist",
    description: "Generate a presentation and disclosure checklist",
    prompt: "Generate a checklist of required disclosures under IFRS for this specific accounting area (e.g., Property, Plant, and Equipment, Leases).",
    category: "ca",
    hostApp: "Word",
    icon: "📋",
  },
  {
    id: "ca-consolidation",
    title: "Consolidation Assistant",
    description: "Help with group consolidation entries",
    prompt: "Assist with preparing consolidated financial statements. Suggest the necessary elimination entries for intercompany transactions, balances, and unrealized profits.",
    category: "ca",
    hostApp: "Excel",
    icon: "🔗",
  },
  {
    id: "ca-segment-reporting",
    title: "Segment Reporting Helper",
    description: "Identify and report operating segments",
    prompt: "Help apply IFRS 8 Operating Segments. Evaluate the 10% quantitative thresholds to identify reportable segments based on this financial data.",
    category: "ca",
    hostApp: "Excel",
    icon: "🧩",
  },
  {
    id: "ca-related-party",
    title: "Related Party Transaction Identifier",
    description: "Identify required related party disclosures",
    prompt: "Review this list of transactions and identify which ones qualify as related party transactions under IAS 24. Suggest the required disclosures.",
    category: "ca",
    hostApp: "Excel",
    icon: "🤝",
  },
  {
    id: "ca-ifrs-15-16",
    title: "IFRS 15/16 Revenue/Lease Assistant",
    description: "Apply complex revenue and lease standards",
    prompt: "Analyze this contract under IFRS 15 (Revenue) or IFRS 16 (Leases). Break down the 5-step revenue model or the lease liability/ROU asset calculation.",
    category: "ca",
    hostApp: "Excel",
    icon: "🏢",
  },
  {
    id: "ca-ias-36",
    title: "IAS 36 Impairment Checker",
    description: "Assist with impairment testing",
    prompt: "Help perform an impairment test under IAS 36. Compare the carrying amount to the recoverable amount (higher of Value in Use or Fair Value less costs to sell).",
    category: "ca",
    hostApp: "Excel",
    icon: "📉",
  },
  {
    id: "bd-nbr-tax",
    title: "NBR Tax Computation",
    description: "Assist with Bangladesh corporate/individual tax",
    prompt: "Assist with calculating tax liability under the Income Tax Act, 2023 of Bangladesh. Consider allowable deductions, inadmissible expenses, and applicable tax rates.",
    category: "compliance-bd",
    hostApp: "Excel",
    icon: "🇧🇩",
  },
  {
    id: "bd-vat-return",
    title: "VAT Return Helper",
    description: "Help with Mushak 9.1 and VAT compliance",
    prompt: "Help prepare data for the Bangladesh VAT return (Mushak 9.1). Identify output VAT, input tax credit eligibility, VDS deductions, and decreasing adjustments.",
    category: "compliance-bd",
    hostApp: "Excel",
    icon: "🧾",
  },
  {
    id: "bd-tds-checker",
    title: "TDS Entry Checker",
    description: "Verify Tax Deducted at Source entries",
    prompt: "Review these transactions for compliance with Bangladesh TDS/VDS regulations. Specify the correct section, rate, and base amount for deduction.",
    category: "compliance-bd",
    hostApp: "Excel",
    icon: "✂️",
  },
  {
    id: "bd-companies-act",
    title: "Companies Act Compliance",
    description: "Check compliance with BD Companies Act 1994",
    prompt: "Review this corporate action or meeting minutes for compliance with the Bangladesh Companies Act, 1994. Highlight any missing statutory requirements or filings.",
    category: "compliance-bd",
    hostApp: "Word",
    icon: "⚖️",
  },
  {
    id: "cross-qa",
    title: "Document Q&A",
    description: "Ask questions about the document",
    prompt: "Based on this document/data, answer the following question: [Your Question].",
    category: "general",
    hostApp: "All",
    icon: "❓",
  },
  {
    id: "cross-terminology",
    title: "Terminology Explainer",
    description: "Explain industry jargon",
    prompt: "Explain the following industry jargon, acronyms, or technical terms found in this document in plain language.",
    category: "general",
    hostApp: "All",
    icon: "📖",
  },
  {
    id: "cross-email-tone",
    title: "Professional Email Tone Checker",
    description: "Check tone before sending",
    prompt: "Review this draft email. Is the tone appropriate for [Audience]? Suggest edits to make it more professional and effective.",
    category: "writing",
    hostApp: "All",
    icon: "📧",
  },
  {
    id: "cross-translation",
    title: "English/Bengali Translation",
    description: "Translate business text",
    prompt: "Translate this business text accurately between English and Bengali, maintaining professional terminology.",
    category: "translate",
    hostApp: "All",
    icon: "🌐",
  },
  {
    id: "cross-agenda",
    title: "Meeting Agenda Writer",
    description: "Draft a meeting agenda",
    prompt: "Draft a structured meeting agenda for a 60-minute meeting about [Topic]. Include time allocations for each item.",
    category: "general",
    hostApp: "All",
    icon: "🗓️",
  },
  {
    id: "cross-sop",
    title: "SOP Drafter",
    description: "Draft a Standard Operating Procedure",
    prompt: "Draft a Standard Operating Procedure (SOP) for the following process. Include: Purpose, Scope, Responsibilities, and Step-by-step Procedure.",
    category: "general",
    hostApp: "All",
    icon: "⚙️",
  },
  {
    id: "cross-process",
    title: "Process Documentation Assistant",
    description: "Document a business process",
    prompt: "Convert these rough notes about a workflow into a clear, numbered process document.",
    category: "general",
    hostApp: "All",
    icon: "📝",
  },
  {
    id: "cross-action-points",
    title: "Minutes to Action Points",
    description: "Extract action items from text",
    prompt: "Read these meeting minutes and extract a clear list of Action Items, assigning an owner and deadline to each if mentioned.",
    category: "general",
    hostApp: "All",
    icon: "🎯",
  },
  {
    id: "cross-checklist",
    title: "Checklist Generator",
    description: "Generate a checklist from requirements",
    prompt: "Generate a comprehensive step-by-step checklist based on these requirements or process description.",
    category: "general",
    hostApp: "All",
    icon: "✅",
  },
  {
    id: "cross-risk",
    title: "Risk Register Builder",
    description: "Identify project risks",
    prompt: "Based on this project description, suggest 5 potential risks, their likelihood (H/M/L), impact (H/M/L), and proposed mitigation strategies to add to a Risk Register.",
    category: "reporting",
    hostApp: "All",
    icon: "⚠️",
  },
  {
    id: "cross-tracker",
    title: "Project Tracker Assistant",
    description: "Suggest project tracking columns",
    prompt: "Suggest the necessary columns and statuses for a project tracking spreadsheet or table for this type of project.",
    category: "general",
    hostApp: "All",
    icon: "📊",
  },
  {
    id: "cross-stakeholder",
    title: "Stakeholder Communication",
    description: "Draft stakeholder updates",
    prompt: "Draft a concise project update communication tailored for senior stakeholders. Focus on progress, blockers, and next steps.",
    category: "writing",
    hostApp: "All",
    icon: "🗣️",
  },

];

/** Get templates filtered by host app */
export function getTemplatesForHost(host: OfficeHostType): PromptTemplate[] {
  return PROMPT_TEMPLATES.filter(
    (t) => t.hostApp === host || t.hostApp === "All"
  );
}

/** Get templates by category */
export function getTemplatesByCategory(
  category: string,
  host?: OfficeHostType
): PromptTemplate[] {
  let templates = PROMPT_TEMPLATES.filter((t) => t.category === category);
  if (host) {
    templates = templates.filter((t) => t.hostApp === host || t.hostApp === "All");
  }
  return templates;
}

/** Search templates */
export function searchTemplates(query: string, host?: OfficeHostType): PromptTemplate[] {
  const q = query.toLowerCase();
  let templates = PROMPT_TEMPLATES.filter(
    (t) =>
      t.title.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.prompt.toLowerCase().includes(q)
  );
  if (host) {
    templates = templates.filter((t) => t.hostApp === host || t.hostApp === "All");
  }
  return templates;
}
